#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2016
#
# This file is in the public domain.
# 
#############################################################################

# source files in this project (main.cpp is automatically assumed)
SOURCES := rectangle.cpp line.cpp filledrectangle.cpp samengesteldobject.cpp

# header files in this project
HEADERS := rectangle.hpp line.hpp filledrectangle.hpp samengesteldobject.hpp 
#hwlib-graphics-drawables.hpp

# other places to look for files for this project
SEARCH  := 

# set RELATIVE to the next higher directory 
# and defer to the Makefile.* there
RELATIVE := ..
include $(RELATIVE)/Makefile.native
