#!/usr/bin/env bash

rm logfile
for file in *
	do 
		f=*.*
		$1 *.* > /dev/null
	if [ $? -eq 0 ] ; then
		echo "$1 on $file is succesfull with output code: $?" >> logfile
	else
		echo "$1 on $file is failed with output code: $?" >> logfile
	fi
	done

